name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Production Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies Laravel
      # Kode di bawah ini memaksa GitHub masuk ke folder backend terlebih dahulu
      working-directory: ./digiram-backend
      run: composer install --no-dev --optimize-autoloader --no-ansi --no-interaction --no-scripts --prefer-dist

    - name: Sync Files to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/
        # Kode di bawah ini memastikan hanya isi folder backend saja yang di-upload ke InfinityFree
        local-dir: ./digiram-backend/