name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main # Skrip berjalan otomatis setiap kamu melakukan git push ke branch main

jobs:
  web-deploy:
    name: Production Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Sesuaikan dengan versi PHP Laravel kamu

    - name: Install Dependencies Laravel
      run: composer install --no-dev --optimize-autoloader --no-ansi --no-interaction --no-scripts --prefer-dist

    # JIKA KAMU INGIN SEKALIGUS MERAKIT/BUILD FRONTEND DI SERVER GITHUB, AKTIFKAN BAGIAN INI:
    # - name: Install Node.js & Build Front-End
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '18'
    # - run: npm install
    # - run: npm run build

    - name: Sync Files to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/ # Mengirimkan file langsung ke folder htdocs InfinityFree